# Generated by Django 4.1.4 on 2023-06-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
